/* =====================================================================
 * MAFFL SCHEDULE DATA  (2026 regular-season fixtures, both tiers)
 * ---------------------------------------------------------------------
 * Sources: data/MAFFL_Schedule_2026_Upper.csv (84 rows, commissioner-authored)
 *          data/MAFFL_Schedule_2026_Lower.csv (70 rows, one-time ESPN extract)
 * FIXTURES ARE NOT RESULTS. This says who is scheduled to meet; it carries
 * no scores and no W/L. Records, streaks and ratings come only from played
 * results (matchups-data.js). MAFFL Ghost (Lower-Tier bye filler) is kept
 * here so the weekly slate is complete; it is not an owner.
 * Each game (6 fields):
 *   [week, tier, awayOwner, homeOwner, gameClass, division]
 *   week      : integer week number (1-14)
 *   tier      : "U" = Upper, "L" = Lower
 *   awayOwner : registry canonical_name (or "MAFFL Ghost")
 *   homeOwner : registry canonical_name (or "MAFFL Ghost")
 *   gameClass : "Divisional", "Open" or "Mirror Match" (verbatim Game_Class)
 *   division  : Upper division letter on Divisional games, else ""
 * Sorted by week, then tier (U first), then source row order.
 * Regenerate with build/generate-schedule-data.ps1 -Write; do not hand-edit.
 * ===================================================================== */
window.SCHEDULE_DATA = {
  year: 2026,
  games: [
    [1,"U","Mike Murello","David Murello","Divisional","A"],
    [1,"U","Tony Trozzo","Dan Reilly","Divisional","C"],
    [1,"U","Brian Murello / Ron Murello","Ed Peters","Divisional","D"],
    [1,"U","Jon Fetrow","Jon Murello / Rick Simmons","Open",""],
    [1,"U","Joe Reilly","Jacob Nickman","Open",""],
    [1,"U","Braiden Snyder","BJ Funari","Mirror Match",""],
    [1,"L","Bob Keslar","Ben Funari","Open",""],
    [1,"L","Dominic Nicastro","Sam Lavrinc","Open",""],
    [1,"L","Todd Trozzo","Tony Brooks","Open",""],
    [1,"L","MAFFL Ghost","Charles Lavrinc","Open",""],
    [1,"L","Chris Johnson","Nick Yankovich","Open",""],
    [2,"U","Braiden Snyder","Jacob Nickman","Divisional","B"],
    [2,"U","Tony Trozzo","Joe Reilly","Divisional","C"],
    [2,"U","Ed Peters","Jon Fetrow","Divisional","D"],
    [2,"U","Jon Murello / Rick Simmons","Mike Murello","Open",""],
    [2,"U","David Murello","Brian Murello / Ron Murello","Mirror Match",""],
    [2,"U","BJ Funari","Dan Reilly","Open",""],
    [2,"L","Dominic Nicastro","Bob Keslar","Open",""],
    [2,"L","Ben Funari","Todd Trozzo","Open",""],
    [2,"L","Sam Lavrinc","MAFFL Ghost","Open",""],
    [2,"L","Tony Brooks","Chris Johnson","Open",""],
    [2,"L","Charles Lavrinc","Nick Yankovich","Open",""],
    [3,"U","BJ Funari","David Murello","Divisional","A"],
    [3,"U","Jacob Nickman","Jon Murello / Rick Simmons","Divisional","B"],
    [3,"U","Jon Fetrow","Brian Murello / Ron Murello","Divisional","D"],
    [3,"U","Mike Murello","Tony Trozzo","Open",""],
    [3,"U","Ed Peters","Joe Reilly","Open",""],
    [3,"U","Dan Reilly","Braiden Snyder","Open",""],
    [3,"L","Bob Keslar","Todd Trozzo","Open",""],
    [3,"L","MAFFL Ghost","Dominic Nicastro","Open",""],
    [3,"L","Chris Johnson","Ben Funari","Open",""],
    [3,"L","Nick Yankovich","Sam Lavrinc","Open",""],
    [3,"L","Charles Lavrinc","Tony Brooks","Open",""],
    [4,"U","Mike Murello","BJ Funari","Divisional","A"],
    [4,"U","Braiden Snyder","Jon Murello / Rick Simmons","Divisional","B"],
    [4,"U","Joe Reilly","Dan Reilly","Divisional","C"],
    [4,"U","Tony Trozzo","Jon Fetrow","Open",""],
    [4,"U","Brian Murello / Ron Murello","Jacob Nickman","Open",""],
    [4,"U","David Murello","Ed Peters","Open",""],
    [4,"L","MAFFL Ghost","Bob Keslar","Open",""],
    [4,"L","Todd Trozzo","Chris Johnson","Open",""],
    [4,"L","Dominic Nicastro","Nick Yankovich","Open",""],
    [4,"L","Ben Funari","Charles Lavrinc","Open",""],
    [4,"L","Sam Lavrinc","Tony Brooks","Open",""],
    [5,"U","Joe Reilly","Mike Murello","Mirror Match",""],
    [5,"U","Jon Murello / Rick Simmons","Tony Trozzo","Mirror Match",""],
    [5,"U","Jacob Nickman","Jon Fetrow","Mirror Match",""],
    [5,"U","Dan Reilly","David Murello","Open",""],
    [5,"U","Brian Murello / Ron Murello","Braiden Snyder","Open",""],
    [5,"U","Ed Peters","BJ Funari","Open",""],
    [5,"L","Bob Keslar","Chris Johnson","Open",""],
    [5,"L","Nick Yankovich","MAFFL Ghost","Open",""],
    [5,"L","Charles Lavrinc","Todd Trozzo","Open",""],
    [5,"L","Tony Brooks","Dominic Nicastro","Open",""],
    [5,"L","Sam Lavrinc","Ben Funari","Open",""],
    [6,"U","Jon Fetrow","Mike Murello","Open",""],
    [6,"U","Jon Murello / Rick Simmons","Joe Reilly","Open",""],
    [6,"U","Jacob Nickman","Tony Trozzo","Open",""],
    [6,"U","David Murello","Braiden Snyder","Open",""],
    [6,"U","BJ Funari","Brian Murello / Ron Murello","Open",""],
    [6,"U","Ed Peters","Dan Reilly","Mirror Match",""],
    [6,"L","Nick Yankovich","Bob Keslar","Open",""],
    [6,"L","Chris Johnson","Charles Lavrinc","Open",""],
    [6,"L","MAFFL Ghost","Tony Brooks","Open",""],
    [6,"L","Todd Trozzo","Sam Lavrinc","Open",""],
    [6,"L","Dominic Nicastro","Ben Funari","Open",""],
    [7,"U","Mike Murello","Jacob Nickman","Open",""],
    [7,"U","David Murello","Jon Murello / Rick Simmons","Open",""],
    [7,"U","Joe Reilly","Jon Fetrow","Open",""],
    [7,"U","Tony Trozzo","BJ Funari","Open",""],
    [7,"U","Dan Reilly","Brian Murello / Ron Murello","Open",""],
    [7,"U","Braiden Snyder","Ed Peters","Open",""],
    [7,"L","Bob Keslar","Charles Lavrinc","Open",""],
    [7,"L","Tony Brooks","Nick Yankovich","Open",""],
    [7,"L","Sam Lavrinc","Chris Johnson","Open",""],
    [7,"L","Ben Funari","MAFFL Ghost","Open",""],
    [7,"L","Dominic Nicastro","Todd Trozzo","Open",""],
    [8,"U","Dan Reilly","Mike Murello","Open",""],
    [8,"U","BJ Funari","Jon Murello / Rick Simmons","Open",""],
    [8,"U","Brian Murello / Ron Murello","Joe Reilly","Open",""],
    [8,"U","Tony Trozzo","Braiden Snyder","Open",""],
    [8,"U","Jacob Nickman","Ed Peters","Open",""],
    [8,"U","Jon Fetrow","David Murello","Open",""],
    [8,"L","Tony Brooks","Bob Keslar","Open",""],
    [8,"L","Charles Lavrinc","Sam Lavrinc","Open",""],
    [8,"L","Nick Yankovich","Ben Funari","Open",""],
    [8,"L","Chris Johnson","Dominic Nicastro","Open",""],
    [8,"L","MAFFL Ghost","Todd Trozzo","Open",""],
    [9,"U","Braiden Snyder","Mike Murello","Open",""],
    [9,"U","Jon Murello / Rick Simmons","Brian Murello / Ron Murello","Open",""],
    [9,"U","Joe Reilly","BJ Funari","Open",""],
    [9,"U","Ed Peters","Tony Trozzo","Open",""],
    [9,"U","David Murello","Jacob Nickman","Open",""],
    [9,"U","Jon Fetrow","Dan Reilly","Open",""],
    [9,"L","Bob Keslar","Sam Lavrinc","Open",""],
    [9,"L","Ben Funari","Tony Brooks","Open",""],
    [9,"L","Dominic Nicastro","Charles Lavrinc","Open",""],
    [9,"L","Todd Trozzo","Nick Yankovich","Open",""],
    [9,"L","MAFFL Ghost","Chris Johnson","Open",""],
    [10,"U","Mike Murello","Ed Peters","Open",""],
    [10,"U","Jon Murello / Rick Simmons","Dan Reilly","Open",""],
    [10,"U","Joe Reilly","David Murello","Open",""],
    [10,"U","Brian Murello / Ron Murello","Tony Trozzo","Open",""],
    [10,"U","Jacob Nickman","BJ Funari","Open",""],
    [10,"U","Braiden Snyder","Jon Fetrow","Open",""],
    [10,"L","Ben Funari","Bob Keslar","Open",""],
    [10,"L","Sam Lavrinc","Dominic Nicastro","Open",""],
    [10,"L","Tony Brooks","Todd Trozzo","Open",""],
    [10,"L","Charles Lavrinc","MAFFL Ghost","Open",""],
    [10,"L","Nick Yankovich","Chris Johnson","Open",""],
    [11,"U","Mike Murello","Joe Reilly","Mirror Match",""],
    [11,"U","Tony Trozzo","Jon Murello / Rick Simmons","Mirror Match",""],
    [11,"U","Jon Fetrow","Jacob Nickman","Mirror Match",""],
    [11,"U","Brian Murello / Ron Murello","David Murello","Mirror Match",""],
    [11,"U","Dan Reilly","Ed Peters","Mirror Match",""],
    [11,"U","BJ Funari","Braiden Snyder","Mirror Match",""],
    [11,"L","Bob Keslar","Dominic Nicastro","Open",""],
    [11,"L","Todd Trozzo","Ben Funari","Open",""],
    [11,"L","MAFFL Ghost","Sam Lavrinc","Open",""],
    [11,"L","Chris Johnson","Tony Brooks","Open",""],
    [11,"L","Nick Yankovich","Charles Lavrinc","Open",""],
    [12,"U","David Murello","Mike Murello","Divisional","A"],
    [12,"U","Jon Murello / Rick Simmons","Braiden Snyder","Divisional","B"],
    [12,"U","Joe Reilly","Tony Trozzo","Divisional","C"],
    [12,"U","Ed Peters","Brian Murello / Ron Murello","Divisional","D"],
    [12,"U","Jacob Nickman","Dan Reilly","Open",""],
    [12,"U","BJ Funari","Jon Fetrow","Open",""],
    [12,"L","Todd Trozzo","Bob Keslar","Open",""],
    [12,"L","Dominic Nicastro","MAFFL Ghost","Open",""],
    [12,"L","Ben Funari","Chris Johnson","Open",""],
    [12,"L","Sam Lavrinc","Nick Yankovich","Open",""],
    [12,"L","Tony Brooks","Charles Lavrinc","Open",""],
    [13,"U","David Murello","BJ Funari","Divisional","A"],
    [13,"U","Jon Murello / Rick Simmons","Jacob Nickman","Divisional","B"],
    [13,"U","Dan Reilly","Tony Trozzo","Divisional","C"],
    [13,"U","Jon Fetrow","Ed Peters","Divisional","D"],
    [13,"U","Mike Murello","Brian Murello / Ron Murello","Open",""],
    [13,"U","Braiden Snyder","Joe Reilly","Open",""],
    [13,"L","Bob Keslar","MAFFL Ghost","Open",""],
    [13,"L","Chris Johnson","Todd Trozzo","Open",""],
    [13,"L","Nick Yankovich","Dominic Nicastro","Open",""],
    [13,"L","Charles Lavrinc","Ben Funari","Open",""],
    [13,"L","Tony Brooks","Sam Lavrinc","Open",""],
    [14,"U","BJ Funari","Mike Murello","Divisional","A"],
    [14,"U","Jacob Nickman","Braiden Snyder","Divisional","B"],
    [14,"U","Dan Reilly","Joe Reilly","Divisional","C"],
    [14,"U","Brian Murello / Ron Murello","Jon Fetrow","Divisional","D"],
    [14,"U","Ed Peters","Jon Murello / Rick Simmons","Open",""],
    [14,"U","Tony Trozzo","David Murello","Open",""],
    [14,"L","Chris Johnson","Bob Keslar","Open",""],
    [14,"L","MAFFL Ghost","Nick Yankovich","Open",""],
    [14,"L","Todd Trozzo","Charles Lavrinc","Open",""],
    [14,"L","Dominic Nicastro","Tony Brooks","Open",""],
    [14,"L","Ben Funari","Sam Lavrinc","Open",""]
  ]
};
